name: Merge develop branch to master
on:
  push:
    branches:
      - 'develop'
jobs:
  merge-develop-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> master
        run: |
          git fetch
          git checkout master
          git merge develop
          git push
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
